---
- hosts: localhost
  gather_facts: no
  connection: local 
  vars:
    region: ap-southeast-1
    name: i-0f73991ac3f261f98
  tasks:
    - name: get instance id
      instance_lookup:
        region: "{{ region }}"
        tags:
          Name: "{{ name }}"
      register: instanceid

    - debug: var=instanceid.instance_ids

    - name: start instance
      ec2:
        region: "{{ region }}"
        instance_ids: "{{ instanceid.instance_ids }}"
        state: running
        wait: yes
      when: instanceid is defined

