---  
- hosts: localhost  
  gather_facts: no    
  connection: local 
  vars:  
    region: ap-southeast-1    
    name: i-0dc3f379e63c59d59
  tasks:  
    #- name: get instance id
     # command: aws ec2 describe-instances --filter Name=tag:Name,Values={{ name }} 
      #         --query 'Reservations[0].Instances[0].InstanceId' --output text
    # register: i-01666e5a15cf63062

    - name: start instance 
      ec2:  
        region: "{{ region }}"
        instance_ids: "{{ instanceid.stdout }}"  
        state: running
        wait: yes
      when: instanceid.stdout!="None"
