---  
- hosts: localhost  
  gather_facts: no    
  connection: local 
  tasks:
    - name: create IAM user yash
      iam:
        iam_type: user
        name: yash
        state: present
        groups: admin

