---  
- hosts: localhost  
  connection: local  
  gather_facts: no  
  vars:
    region: ap-southeast-1
    keyname: testing
  tasks:  
    - name: create key pair  
      ec2_key:
        region: "{{ region }}"
        name: "{{ keyname }}"
      register: testing

    - name: write to file
      copy: content="{{ mykey.key.private_key }}" dest="~/.ssh/{{ keyname }}.pem" mode=0600
      when: testing.changed
   
