---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    #your region  
    region: ap-southeast-1    
  tasks:  
    - name: EC2 basic provisioning  
      ec2:
        region: "{{ region }}"  
        key_name: sqlbackup 
        instance_type: t1.micro  
        image: ami-05c859630889c79c8
        wait: yes    
        group: ansible
        instance_tags:  
          group: ansible
        exact_count: 1  
        count_tag:  
          group: ansible
